services:
  - type: web
    name: radarmarket
    env: node
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20.0.0
      - key: DATABASE_URL
        fromDatabase:
          name: radarmarket-db
          property: connectionString
    plan: free

databases:
  - name: radarmarket-db
    databaseName: radarmarket
    user: radarmarket_user
    plan: free
