services:
  - type: web
    name: radarmarket
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    plan: free
